const countriesData = [
    { name: "Afganistán", capital: "Kabul", code: "af", lat: 34.5, lon: 69.1 },
    { name: "Albania", capital: "Tirana", code: "al", lat: 41.3, lon: 19.8 },
    { name: "Alemania", capital: "Berlín", code: "de", lat: 52.5, lon: 13.4 },
    { name: "Andorra", capital: "Andorra la Vieja", code: "ad", lat: 42.5, lon: 1.5 },
    { name: "Angola", capital: "Luanda", code: "ao", lat: -8.8, lon: 13.2 },
    { name: "Antigua y Barbuda", capital: "Saint John", code: "ag", lat: 17.1, lon: -61.8 },
    { name: "Arabia Saudita", capital: "Riad", code: "sa", lat: 24.7, lon: 46.7 },
    { name: "Argelia", capital: "Argel", code: "dz", lat: 36.7, lon: 3.0 },
    { name: "Argentina", capital: "Buenos Aires", code: "ar", lat: -34.6, lon: -58.4 },
    { name: "Armenia", capital: "Ereván", code: "am", lat: 40.1, lon: 44.5 },
    { name: "Australia", capital: "Camberra", code: "au", lat: -35.3, lon: 149.1 },
    { name: "Austria", capital: "Viena", code: "at", lat: 48.2, lon: 16.3 },
    { name: "Azerbaiyán", capital: "Bakú", code: "az", lat: 40.4, lon: 49.8 },
    { name: "Bahamas", capital: "Nasáu", code: "bs", lat: 25.0, lon: -77.3 },
    { name: "Bangladés", capital: "Daca", code: "bd", lat: 23.8, lon: 90.4 },
    { name: "Barbados", capital: "Bridgetown", code: "bb", lat: 13.1, lon: -59.6 },
    { name: "Baréin", capital: "Manama", code: "bh", lat: 26.2, lon: 50.5 },
    { name: "Bélgica", capital: "Bruselas", code: "be", lat: 50.8, lon: 4.3 },
    { name: "Belice", capital: "Belmopán", code: "bz", lat: 17.2, lon: -88.7 },
    { name: "Benín", capital: "Porto Novo", code: "bj", lat: 6.4, lon: 2.6 },
    { name: "Bielorrusia", capital: "Minsk", code: "by", lat: 53.9, lon: 27.5 },
    { name: "Birmania", capital: "Naypyidó", code: "mm", lat: 19.7, lon: 96.1 },
    { name: "Bolivia", capital: "Sucre", code: "bo", lat: -16.5, lon: -68.1 },
    { name: "Bosnia y Herzegovina", capital: "Sarajevo", code: "ba", lat: 43.8, lon: 18.3 },
    { name: "Botsuana", capital: "Gaborone", code: "bw", lat: -24.6, lon: 25.9 },
    { name: "Brasil", capital: "Brasilia", code: "br", lat: -15.7, lon: -47.8 },
    { name: "Brunéi", capital: "Bandar Seri Begawan", code: "bn", lat: 4.8, lon: 114.9 },
    { name: "Bulgaria", capital: "Sofía", code: "bg", lat: 42.7, lon: 23.3 },
    { name: "Burkina Faso", capital: "Uagadugú", code: "bf", lat: 12.3, lon: -1.5 },
    { name: "Burundi", capital: "Guitega", code: "bi", lat: -3.3, lon: 29.3 },
    { name: "Bután", capital: "Timbu", code: "bt", lat: 27.4, lon: 89.6 },
    { name: "Cabo Verde", capital: "Praia", code: "cv", lat: 14.9, lon: -23.5 },
    { name: "Camboya", capital: "Nom Pen", code: "kh", lat: 11.5, lon: 104.8 },
    { name: "Camerún", capital: "Yaundé", code: "cm", lat: 3.8, lon: 11.5 },
    { name: "Canadá", capital: "Ottawa", code: "ca", lat: 45.4, lon: -75.6 },
    { name: "Catar", capital: "Doha", code: "qa", lat: 25.2, lon: 51.5 },
    { name: "Chad", capital: "Yamena", code: "td", lat: 12.1, lon: 15.0 },
    { name: "Chile", capital: "Santiago", code: "cl", lat: -33.4, lon: -70.6 },
    { name: "China", capital: "Pekín", code: "cn", lat: 39.9, lon: 116.4 },
    { name: "Chipre", capital: "Nicosia", code: "cy", lat: 35.1, lon: 33.3 },
    { name: "Ciudad del Vaticano", capital: "Ciudad del Vaticano", code: "va", lat: 41.9, lon: 12.4 },
    { name: "Colombia", capital: "Bogotá", code: "co", lat: 4.7, lon: -74.0 },
    { name: "Comoras", capital: "Moroni", code: "km", lat: -11.7, lon: 43.2 },
    { name: "Corea del Norte", capital: "Pyongyang", code: "kp", lat: 39.0, lon: 125.7 },
    { name: "Corea del Sur", capital: "Seúl", code: "kr", lat: 37.5, lon: 126.9 },
    { name: "Costa de Marfil", capital: "Yamusukro", code: "ci", lat: 6.8, lon: -5.2 },
    { name: "Costa Rica", capital: "San José", code: "cr", lat: 9.9, lon: -84.0 },
    { name: "Croacia", capital: "Zagreb", code: "hr", lat: 45.8, lon: 15.9 },
    { name: "Cuba", capital: "La Habana", code: "cu", lat: 23.1, lon: -82.3 },
    { name: "Dinamarca", capital: "Copenhague", code: "dk", lat: 55.6, lon: 12.5 },
    { name: "Dominica", capital: "Roseau", code: "dm", lat: 15.3, lon: -61.3 },
    { name: "Ecuador", capital: "Quito", code: "ec", lat: -0.1, lon: -78.4 },
    { name: "Egipto", capital: "El Cairo", code: "eg", lat: 30.0, lon: 31.2 },
    { name: "El Salvador", capital: "San Salvador", code: "sv", lat: 13.6, lon: -89.1 },
    { name: "Emiratos Árabes Unidos", capital: "Abu Dabi", code: "ae", lat: 24.4, lon: 54.3 },
    { name: "Eritrea", capital: "Asmara", code: "er", lat: 15.3, lon: 38.9 },
    { name: "Eslovaquia", capital: "Bratislava", code: "sk", lat: 48.1, lon: 17.1 },
    { name: "Eslovenia", capital: "Liubliana", code: "si", lat: 46.0, lon: 14.5 },
    { name: "España", capital: "Madrid", code: "es", lat: 40.4, lon: -3.7 },
    { name: "Estados Unidos", capital: "Washington D.C.", code: "us", lat: 38.9, lon: -77.0 },
    { name: "Estonia", capital: "Tallin", code: "ee", lat: 59.4, lon: 24.7 },
    { name: "Etiopía", capital: "Adís Abeba", code: "et", lat: 9.0, lon: 38.7 },
    { name: "Filipinas", capital: "Manila", code: "ph", lat: 14.5, lon: 120.9 },
    { name: "Finlandia", capital: "Helsinki", code: "fi", lat: 60.1, lon: 24.9 },
    { name: "Fiyi", capital: "Suva", code: "fj", lat: -18.1, lon: 178.4 },
    { name: "Francia", capital: "París", code: "fr", lat: 48.8, lon: 2.3 },
    { name: "Gabón", capital: "Libreville", code: "ga", lat: 0.3, lon: 9.4 },
    { name: "Gambia", capital: "Banjul", code: "gm", lat: 13.4, lon: -16.5 },
    { name: "Georgia", capital: "Tiflis", code: "ge", lat: 41.7, lon: 44.8 },
    { name: "Ghana", capital: "Acra", code: "gh", lat: 5.6, lon: -0.2 },
    { name: "Granada", capital: "Saint George", code: "gd", lat: 12.0, lon: -61.7 },
    { name: "Grecia", capital: "Atenas", code: "gr", lat: 37.9, lon: 23.7 },
    { name: "Guatemala", capital: "Ciudad de Guatemala", code: "gt", lat: 14.6, lon: -90.5 },
    { name: "Guinea", capital: "Conakri", code: "gn", lat: 9.5, lon: -13.7 },
    { name: "Guinea-Bisáu", capital: "Bisáu", code: "gw", lat: 11.8, lon: -15.5 },
    { name: "Guinea Ecuatorial", capital: "Malabo", code: "gq", lat: 3.7, lon: 8.7 },
    { name: "Guyana", capital: "Georgetown", code: "gy", lat: 6.8, lon: -58.1 },
    { name: "Haití", capital: "Puerto Príncipe", code: "ht", lat: 18.5, lon: -72.3 },
    { name: "Honduras", capital: "Tegucigalpa", code: "hn", lat: 14.1, lon: -87.2 },
    { name: "Hungría", capital: "Budapest", code: "hu", lat: 47.5, lon: 19.0 },
    { name: "India", capital: "Nueva Delhi", code: "in", lat: 28.6, lon: 77.2 },
    { name: "Indonesia", capital: "Yakarta", code: "id", lat: -6.2, lon: 106.8 },
    { name: "Irak", capital: "Bagdad", code: "iq", lat: 33.3, lon: 44.4 },
    { name: "Irán", capital: "Teherán", code: "ir", lat: 35.7, lon: 51.4 },
    { name: "Irlanda", capital: "Dublín", code: "ie", lat: 53.3, lon: -6.2 },
    { name: "Islandia", capital: "Reikiavik", code: "is", lat: 64.1, lon: -21.9 },
    { name: "Islas Marshall", capital: "Majuro", code: "mh", lat: 7.1, lon: 171.3 },
    { name: "Islas Salomón", capital: "Honiara", code: "sb", lat: -9.4, lon: 159.9 },
    { name: "Israel", capital: "Jerusalén", code: "il", lat: 31.7, lon: 35.2 },
    { name: "Italia", capital: "Roma", code: "it", lat: 41.9, lon: 12.5 },
    { name: "Jamaica", capital: "Kingston", code: "jm", lat: 18.0, lon: -76.8 },
    { name: "Japón", capital: "Tokio", code: "jp", lat: 35.6, lon: 139.7 },
    { name: "Jordania", capital: "Amán", code: "jo", lat: 31.9, lon: 35.9 },
    { name: "Kazajistán", capital: "Nur-Sultán", code: "kz", lat: 51.1, lon: 71.4 },
    { name: "Kenia", capital: "Nairobi", code: "ke", lat: -1.2, lon: 36.8 },
    { name: "Kirguistán", capital: "Biskek", code: "kg", lat: 42.8, lon: 74.6 },
    { name: "Kiribati", capital: "Tarawa", code: "ki", lat: 1.3, lon: 173.0 },
    { name: "Kuwait", capital: "Kuwait City", code: "kw", lat: 29.3, lon: 47.9 },
    { name: "Laos", capital: "Vientián", code: "la", lat: 17.9, lon: 102.6 },
    { name: "Lesoto", capital: "Maseru", code: "ls", lat: -29.3, lon: 27.4 },
    { name: "Letonia", capital: "Riga", code: "lv", lat: 56.9, lon: 24.1 },
    { name: "Líbano", capital: "Beirut", code: "lb", lat: 33.8, lon: 35.5 },
    { name: "Liberia", capital: "Monrovia", code: "lr", lat: 6.3, lon: -10.8 },
    { name: "Libia", capital: "Trípoli", code: "ly", lat: 32.8, lon: 13.1 },
    { name: "Liechtenstein", capital: "Vaduz", code: "li", lat: 47.1, lon: 9.5 },
    { name: "Lituania", capital: "Vilna", code: "lt", lat: 54.6, lon: 25.2 },
    { name: "Luxemburgo", capital: "Luxemburgo", code: "lu", lat: 49.6, lon: 6.1 },
    { name: "Macedonia del Norte", capital: "Skopie", code: "mk", lat: 42.0, lon: 21.4 },
    { name: "Madagascar", capital: "Antananarivo", code: "mg", lat: -18.8, lon: 47.5 },
    { name: "Malasia", capital: "Kuala Lumpur", code: "my", lat: 3.1, lon: 101.7 },
    { name: "Malaui", capital: "Lilongüe", code: "mw", lat: -13.9, lon: 33.7 },
    { name: "Maldivas", capital: "Malé", code: "mv", lat: 4.1, lon: 73.5 },
    { name: "Malí", capital: "Bamako", code: "ml", lat: 12.6, lon: -8.0 },
    { name: "Malta", capital: "La Valeta", code: "mt", lat: 35.9, lon: 14.5 },
    { name: "Marruecos", capital: "Rabat", code: "ma", lat: 34.0, lon: -6.8 },
    { name: "Mauricio", capital: "Port Louis", code: "mu", lat: -20.1, lon: 57.5 },
    { name: "Mauritania", capital: "Nuakchot", code: "mr", lat: 18.0, lon: -15.9 },
    { name: "México", capital: "Ciudad de México", code: "mx", lat: 19.4, lon: -99.1 },
    { name: "Micronesia", capital: "Palikir", code: "fm", lat: 6.9, lon: 158.2 },
    { name: "Moldavia", capital: "Chisinau", code: "md", lat: 47.0, lon: 28.8 },
    { name: "Mónaco", capital: "Mónaco", code: "mc", lat: 43.7, lon: 7.4 },
    { name: "Mongolia", capital: "Ulán Bator", code: "mn", lat: 47.9, lon: 106.9 },
    { name: "Montenegro", capital: "Podgorica", code: "me", lat: 42.4, lon: 19.2 },
    { name: "Mozambique", capital: "Maputo", code: "mz", lat: -25.9, lon: 32.5 },
    { name: "Namibia", capital: "Windhoek", code: "na", lat: -22.5, lon: 17.0 },
    { name: "Nauru", capital: "Yaren", code: "nr", lat: -0.5, lon: 166.9 },
    { name: "Nepal", capital: "Katmandú", code: "np", lat: 27.7, lon: 85.3 },
    { name: "Nicaragua", capital: "Managua", code: "ni", lat: 12.1, lon: -86.2 },
    { name: "Níger", capital: "Niamey", code: "ne", lat: 13.5, lon: 2.1 },
    { name: "Nigeria", capital: "Abuya", code: "ng", lat: 9.0, lon: 7.4 },
    { name: "Noruega", capital: "Oslo", code: "no", lat: 59.9, lon: 10.7 },
    { name: "Nueva Zelanda", capital: "Wellington", code: "nz", lat: -41.2, lon: 174.7 },
    { name: "Omán", capital: "Mascate", code: "om", lat: 23.6, lon: 58.5 },
    { name: "Países Bajos", capital: "Ámsterdam", code: "nl", lat: 52.3, lon: 4.8 },
    { name: "Pakistán", capital: "Islamabad", code: "pk", lat: 33.6, lon: 73.0 },
    { name: "Palaos", capital: "Ngerulmud", code: "pw", lat: 7.5, lon: 134.6 },
    { name: "Panamá", capital: "Ciudad de Panamá", code: "pa", lat: 8.9, lon: -79.5 },
    { name: "Papúa Nueva Guinea", capital: "Puerto Moresby", code: "pg", lat: -9.4, lon: 147.1 },
    { name: "Paraguay", capital: "Asunción", code: "py", lat: -25.2, lon: -57.6 },
    { name: "Perú", capital: "Lima", code: "pe", lat: -12.0, lon: -77.0 },
    { name: "Polonia", capital: "Varsovia", code: "pl", lat: 52.2, lon: 21.0 },
    { name: "Portugal", capital: "Lisboa", code: "pt", lat: 38.7, lon: -9.1 },
    { name: "Reino Unido", capital: "Londres", code: "gb", lat: 51.5, lon: -0.1 },
    { name: "República Centroafricana", capital: "Bangui", code: "cf", lat: 4.3, lon: 18.5 },
    { name: "República Checa", capital: "Praga", code: "cz", lat: 50.0, lon: 14.4 },
    { name: "República del Congo", capital: "Brazzaville", code: "cg", lat: -4.2, lon: 15.2 },
    { name: "República Democrática del Congo", capital: "Kinsasa", code: "cd", lat: -4.3, lon: 15.3 },
    { name: "República Dominicana", capital: "Santo Domingo", code: "do", lat: 18.4, lon: -69.8 },
    { name: "Ruanda", capital: "Kigali", code: "rw", lat: -1.9, lon: 30.0 },
    { name: "Rumania", capital: "Bucarest", code: "ro", lat: 44.4, lon: 26.1 },
    { name: "Rusia", capital: "Moscú", code: "ru", lat: 55.7, lon: 37.6 },
    { name: "Samoa", capital: "Apia", code: "ws", lat: -13.8, lon: -171.7 },
    { name: "San Cristóbal y Nieves", capital: "Basseterre", code: "kn", lat: 17.3, lon: -62.7 },
    { name: "San Marino", capital: "San Marino", code: "sm", lat: 43.9, lon: 12.4 },
    { name: "San Vicente y las Granadinas", capital: "Kingstown", code: "vc", lat: 13.1, lon: -61.2 },
    { name: "Santa Lucía", capital: "Castries", code: "lc", lat: 14.0, lon: -60.9 },
    { name: "Santo Tomé y Príncipe", capital: "Santo Tomé", code: "st", lat: 0.3, lon: 6.7 },
    { name: "Senegal", capital: "Dakar", code: "sn", lat: 14.6, lon: -17.4 },
    { name: "Serbia", capital: "Belgrado", code: "rs", lat: 44.8, lon: 20.4 },
    { name: "Seychelles", capital: "Victoria", code: "sc", lat: -4.6, lon: 55.4 },
    { name: "Sierra Leona", capital: "Freetown", code: "sl", lat: 8.4, lon: -13.2 },
    { name: "Singapur", capital: "Singapur", code: "sg", lat: 1.2, lon: 103.8 },
    { name: "Siria", capital: "Damasco", code: "sy", lat: 33.5, lon: 36.2 },
    { name: "Somalia", capital: "Mogadiscio", code: "so", lat: 2.0, lon: 45.3 },
    { name: "Sri Lanka", capital: "Colombo", code: "lk", lat: 6.9, lon: 79.8 },
    { name: "Suazilandia", capital: "Mbabane", code: "sz", lat: -26.3, lon: 31.1 },
    { name: "Sudáfrica", capital: "Pretoria", code: "za", lat: -25.7, lon: 28.2 },
    { name: "Sudán", capital: "Jartum", code: "sd", lat: 15.5, lon: 32.5 },
    { name: "Sudán del Sur", capital: "Yuba", code: "ss", lat: 4.8, lon: 31.6 },
    { name: "Suecia", capital: "Estocolmo", code: "se", lat: 59.3, lon: 18.0 },
    { name: "Suiza", capital: "Berna", code: "ch", lat: 46.9, lon: 7.4 },
    { name: "Surinam", capital: "Paramaribo", code: "sr", lat: 5.8, lon: -55.1 },
    { name: "Tailandia", capital: "Bangkok", code: "th", lat: 13.7, lon: 100.5 },
    { name: "Taiwán", capital: "Taipéi", code: "tw", lat: 25.0, lon: 121.5 },
    { name: "Tanzania", capital: "Dodoma", code: "tz", lat: -6.1, lon: 35.7 },
    { name: "Tayikistán", capital: "Dusambé", code: "tj", lat: 38.5, lon: 68.7 },
    { name: "Timor Oriental", capital: "Dili", code: "tl", lat: -8.5, lon: 125.5 },
    { name: "Togo", capital: "Lomé", code: "tg", lat: 6.1, lon: 1.2 },
    { name: "Tonga", capital: "Nukualofa", code: "to", lat: -21.1, lon: -175.2 },
    { name: "Trinidad y Tobago", capital: "Puerto España", code: "tt", lat: 10.6, lon: -61.5 },
    { name: "Túnez", capital: "Túnez", code: "tn", lat: 36.8, lon: 10.1 },
    { name: "Turkmenistán", capital: "Asjabad", code: "tm", lat: 37.9, lon: 58.3 },
    { name: "Turquía", capital: "Ankara", code: "tr", lat: 39.9, lon: 32.8 },
    { name: "Tuvalu", capital: "Funafuti", code: "tv", lat: -8.5, lon: 179.1 },
    { name: "Ucrania", capital: "Kiev", code: "ua", lat: 50.4, lon: 30.5 },
    { name: "Uganda", capital: "Kampala", code: "ug", lat: 0.3, lon: 32.5 },
    { name: "Uruguay", capital: "Montevideo", code: "uy", lat: -34.8, lon: -56.1 },
    { name: "Uzbekistán", capital: "Taskent", code: "uz", lat: 41.2, lon: 69.2 },
    { name: "Vanuatu", capital: "Port Vila", code: "vu", lat: -17.7, lon: 168.3 },
    { name: "Venezuela", capital: "Caracas", code: "ve", lat: 10.4, lon: -66.9 },
    { name: "Vietnam", capital: "Hanói", code: "vn", lat: 21.0, lon: 105.8 },
    { name: "Yemen", capital: "Saná", code: "ye", lat: 15.3, lon: 44.2 },
    { name: "Yibuti", capital: "Yibuti", code: "dj", lat: 11.5, lon: 43.1 },
    { name: "Zambia", capital: "Lusaka", code: "zm", lat: -15.4, lon: 28.2 },
    { name: "Zimbabue", capital: "Harare", code: "zw", lat: -17.8, lon: 31.0 }
];
